### ISSUE TITLE
Double hyphen in artifact name

### ISSUE THREAD

**Issue by gieza** [DigitalMediaServer/nsis-maven-plugin#1]
The plugin adds double hyphen before classifier in the artifact filename for the artifact being installed into Maven repository.

**Comment by Nadahar** [comment]
@gieza Thank you for your report and for #2. I've been trying to reproduce the problem, but haven't been able to. Looking at #2, I can't quite see which situation it fixes. Can you please enlighten me as to how to get the double hyphen issue?

**Comment by Nadahar** [comment]
@gieza I think I understand now. The problem is that `classifier` is prefixed with a hyphen, which is later used as a parameter for `MavenProjectHelper.attachArtifact()`. `attachArtifact()` probably does its own magic and adds a hyphen as well.

**Comment by Nadahar** [comment]
Fixed in #2.

**Comment by Nadahar** [comment]
Version [1.0.1](https://github.com/DigitalMediaServer/nsis-maven-plugin/releases/tag/v1.0.1) with the fix from #2 has been released and should be available from [Maven Central](https://search.maven.org/artifact/org.digitalmediaserver/nsis-maven-plugin/1.0.1/jar) within a few hours.
