### ISSUE TITLE
makensisExecutable

### ISSUE THREAD

**Issue by mikehenselersimfront** [DigitalMediaServer/nsis-maven-plugin#5]
Plugin does not launch makensis

I have NSIS location properly configured in Windows system PATH.
from any command window i can launch makensis successfully.
....however when using nsis-maven-plugin v1.0.2 it does not recognize makensis.

Setting makensisExecutable works, but i don't want to set this value. 
As per documentation the plugin should launch makensis if its configured in system PATH without having to set <makensisExecutable>

**Comment by Nadahar** [comment]
@mikehenselersimfront There's a known bug with the PATH that there's already a fix for. Unfortunately, I never got any feedback as to whether or not it fixed the problem, so I've never released it. It is available as a `SNAPSHOT` test version though, so if you would try to out and let me know, I'd appreciate it.

I have tested it to the best of my ability and it seems to work, but I'd like somebody else to confirm as well. If it works, I'll release it as `1.0.3`.

You have to add the snapshot-repository to test the `SNAPSHOT` version as I've already explained here: https://github.com/DigitalMediaServer/nsis-maven-plugin/pull/4#issuecomment-644921611

**Comment by mikehenselersimfront** [comment]
I will try It now
I thought maybe it was a long path problem and just installed the NSIS special build…but did not help
My system path is long

**Comment by mikehenselersimfront** [comment]
BEAUTY!
Works for me

thnks

**Comment by Nadahar** [comment]
Great to hear, I'll get working on making a release then :+1:

**Comment by mikehenselersimfront** [comment]
It was just a quick test, I assume everything else will continue to work as expected, nothing broken.

I will continue using the 1.0.3-SNAPSHOT for now

thnks

**Comment by Nadahar** [comment]
I assume the same :wink: I think it should be sound.

You should switch to the release version when it's out, since the SNAPSHOT will be removed eventually. I'll let you know when it's released.

**Comment by mikehenselersimfront** [comment]
Cool, thnks

We were using the old codehaus plugin…but switching now to using yours.
It gives us better flexibility

thnks

**Comment by Nadahar** [comment]
@mikehenselersimfront `1.0.3` has been released to Maven Central. It usually takes some 6-24 hours for their servers to update, but it should appear as soon as their systems have been updated: https://search.maven.org/artifact/org.digitalmediaserver/nsis-maven-plugin/1.0.3/maven-plugin
