### ISSUE TITLE
'defines' parameter missing in plugin.xml for 'make' goal

### ISSUE THREAD

**Issue by direbee** [DigitalMediaServer/nsis-maven-plugin#7]
Doesn't cause an error during build, but IDE flags it as an error.

**Comment by Nadahar** [comment]
I'm not sure what this means, can you shed some more light? What IDE, under which circumstances for example?

**Comment by direbee** [comment]
Sure no problem.  Observed in IntelliJ Community Edition 2020.3.  Typically when viewing a maven pom file in the editor window one can navigate to the definition of each parameter defined for the plugin configuration, eg:
```
        <parameter>
          <name>defines</name>
          <type>java.util.Map</type>
          <required>false</required>
          <editable>true</editable>
          <description>A map of additional defines which will be passed to the execution of
{@code makensis}.</description>
        </parameter>
```
Which ends up in the compiled jar in the following location : "nsis-maven-plugin-1.0.3.jar!\META-INF\maven\plugin.xml"
The 'defines' parameter is present for the 'generate-headerfile' goal, but not for the 'make' goal.  While it still seems to work, it leads to the IDE flagging the <defines> tag as something that doesn't belong in the plugin's configuration, with context action 'Element defines is not allowed here'.

See example plugin configuration below:

```
                    <plugin>
                        <groupId>org.digitalmediaserver</groupId>
                        <artifactId>nsis-maven-plugin</artifactId>
                        <version>1.0.3</version>
                        <executions>
                            <execution>
                                <id>all</id>
                                <goals>
                                    <goal>make</goal>
                                </goals>
                                <configuration>
                                    <attachArtifact>false</attachArtifact>
                                    <scriptFile>some/place/</scriptFile>
                                    <outputFile>foo.exe</outputFile>
                                    <defines>
                                        <NUMVERSION>${numversion}.0</NUMVERSION>
                                        <BUILD>${build}</BUILD>
                                    </defines>
                                    <headerFile>some/file.nsh</headerFile>
                                    <injectHeaderFile>false</injectHeaderFile>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

**Comment by Nadahar** [comment]
I don't quite get this, but then I've never used IntelliJ. That said, the `defines` parameter is only valid for the `generate-headerfile` goal, so if you don't use that goal, there's no point in defining `defines`. Using this goal is optional.

See the [documentation](https://github.com/DigitalMediaServer/nsis-maven-plugin#2-using-the-plugin) for reference.

**Comment by direbee** [comment]
I'll pass that along, thanks.
